### PR TITLE
Chrome Extension v2.0.0 [Social Coding Spring '23 Project]

### PR DESCRIPTION
**Pull request by samyok**
This branch will act as the holding branch while we wait to get google approval. 

We add a bunch of features to the Chrome extension in this update, including:
- Maps on Schedule builder
- adding classes from MyU to Google Calendar
- an options page when clicking on the extension icon in Chrome

Todos after merging this:
 - updating the chrome extension in webstore
 - create marketing materials for it
 - see if the firefox extension can be updated [probably not]

### CODE REVIEW

**Comment by Kanishk-K** [comment]
Do we have any updates to the Google Approval process? It has been longer than a month since our request, are there any avenues for expediting this?

**Comment by samyok** [comment]
No

**Comment by samyok** [comment]
got approved today (~10 min ago). I'll be pushing a few final commits today and then will package this up for testing / deployment :)

**Review by Kanishk-K — APPROVED** [review]
lgtm

**Pull request merged**
