### PR TITLE
GopherGrades v2.1

### PR DESCRIPTION
**Pull request by samyok**
Currently solves: 

- [x] #35 
- [x] #33 
- [x] #32 
- [x] Merges #36

### CODE REVIEW

**Comment by Kanishk-K** [comment]
This merge would also affect issue #37 by pulling pull request #36 .

**Comment by Kanishk-K** [comment]
Notably, before merging there are 2 things regarding displaying SRT information that would be useful. Firstly, the SRT data titles are a little ambiguous and likely mean nothing to our users. Having an on-hover button similar to the COVID popover in order to provide a more direct description would be useful.
image

Furthermore, it is vital that we display the number of responses that comprise the SRT information. There are some courses in which only one SRT evaluation has been done across 7 years, this would obviously be less reliable than a course that has over one hundred responses across 7 years.

**Comment by samyok** [comment]
@Kanishk-K 
image

**Comment by Kanishk-K** [comment]
@JosephMcIndoo I suggested an Idea to @samyok in which SRT data would be more explicitly labeled with the number of responses being written underneath. I like your idea of warning people if the number of responses are really low but I think simply listing a number will allow people to make that decision on their own. Additionally, we actually (for some classes) more SRT responses than the total people taking the class just because we have SRT data from 2015 while grade data only from 2017.

image
Ideally we can put this in the space where the arrow is pointing.
> SRT Information
[NUM_RESPONSES] student responses between Spring 2015 to Fall 2022

**Review by Kanishk-K — APPROVED** [review]

**Review by JosephMcIndoo — APPROVED** [review]

**Review by Jasonchen272 — APPROVED** [review]

**Pull request merged**
