### PR TITLE
Fixed onestop URL to use new University Catalog

### PR DESCRIPTION
**Pull request by apknusel**
I updated the URL for onestop to the University's new Course Catalog System.

### CODE REVIEW

**Comment by samyok** [comment]
Hey @apknusel, sorry for not reviewing this sooner.

The main problem I see with this is that the courseIDs don't map 1:1 from onestop and the new university catalog. 

For example, https://onestop2.umn.edu/pcas/viewCatalogCourse.do?courseId=004765 is the current onestop URL for ENGW1101W, with `004765` being the courseID. However, appending this to the coursedog URL you added creates this url `https://umtc.catalog.prod.coursedog.com/courses/004765`, which does not exist.

Sorry for the delay, feel free to ping me on Discord when you update this 😄

**Review by samyok — CHANGES_REQUESTED** [review]
Hey @apknusel, sorry for not reviewing this sooner.

The main problem I see with this is that the courseIDs don't map 1:1 from onestop and the new university catalog. 

For example, https://onestop2.umn.edu/pcas/viewCatalogCourse.do?courseId=004765 is the current onestop URL for ENGW1101W, with `004765` being the courseID. However, appending this to the coursedog URL you added creates this url `https://umtc.catalog.prod.coursedog.com/courses/004765`, which does not exist.

Sorry for the delay, feel free to ping me on Discord when you update this 😄

**Comment by Kanishk-K** [comment]
Was not aware that Coursedog didn't follow the same indexing as onestop. I wonder if the APAS Api gives insight into the new coursedog ids. Otherwise, we may have to do a cross lookup. I'll do some investigation.

**Comment by apknusel** [comment]
I did some checking, and it seems that the course IDs have an extra number (1) at the end of them in the course catalog. I have tested a bunch of different classes and it seems to work fine.

**Comment by Kanishk-K** [comment]
I'm going to wait before merging, I'll have to see if ASR has modified their API to account for coursedog. I'll respond to this once I've investigated it properly.

**Comment by Kanishk-K** [comment]
Seems like the generation is fine. I stress tested this on the SUM 2023 branch and it seemed to have some database session lock issues due to volume. I'm going to merge this branch over into that and then pull SUM 2023 in.

**Pull request closed without merging**
