### PR TITLE
[UI-UPDATE]: Professors to Instructors in search results

### PR DESCRIPTION
**Pull request by iamBijoyKar**
## Changes 
- Change `frontend/components/Search/SearchResults.jsx` file 
- `Professors` text updated to `Instructors`

## Screenshot
image

### CODE REVIEW

**Comment by iamBijoyKar** [comment]
Please review the PR

**Comment by samyok** [comment]
Please also change the url slug of instructor links to /inst/ and make all the old ones redirect from /prof/x to /inst/x

**Review by samyok — CHANGES_REQUESTED** [review]
.

**Comment by samyok** [comment]
@iamBijoyKar please make sure old links redirect to the new ones

**Comment by iamBijoyKar** [comment]
I already changed the `prof` dir into `inst` in `pages` to update the routes

https://github.com/samyok/gophergrades/assets/85790967/df38a574-d1eb-4fea-9dfd-45909f5fdba4

Otherwise, can you please explain a little more about this?!

**Comment by samyok** [comment]
@iamBijoyKar Basically, I want links to https://umn.lol/prof/x to redirect to https://umn.lol/inst/x -- this would involve changing next.config.js, and making sure that every instance of `/prof/` is changed to `/inst/` :)

Thanks for your changes so far!

**Review by samyok — CHANGES_REQUESTED** [review]
@iamBijoyKar Basically, I want links to https://umn.lol/prof/x to redirect to https://umn.lol/inst/x -- this would involve changing next.config.js, and making sure that every instance of /prof/ is changed to /inst/ :)

Thanks for your changes so far!

**Comment by iamBijoyKar** [comment]
Hey @samyok, I am still new in Nextjs development so I am very sorry for the inconvenience.

**Review by samyok — APPROVED** [review]
Looks good! Thanks

**Comment by Kanishk-K** [comment]
Looks operational on the few professors I tested. LGTM.

**Review by Kanishk-K — APPROVED** [review]

**Pull request merged**
